### PR TITLE
S3 config objects representing binary files must now be declared explicitly

### LINKED ISSUE #98: Error on "create" from 3.1.0
Encountered following error when working with aws-simple :

```
aws-simple--dealer-search--eeee7170: creating CloudFormation changeset...
 ❌  aws-simple--dealer-search--eeee7170 failed: Error [ValidationError]: Template may not exceed 460800 bytes in size.
    at Request.extractError (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/runner/work/dealer-search/dealer-search/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2020-05-27T09:17:59.184Z,
  requestId: 'd2b2659f-d319-4aff-9d19-2db5ea8f3687',
  statusCode: 400,
  retryable: false,
  retryDelay: 173.8271312125218
}
Template may not exceed 460800 bytes in size.
```
This happen when we tried to update to latest version of aws-simple@3.1.0 and aws-cdk@1.41.0 . When using aws-cdk lower than 1.41 the error was:
```
Cloud assembly schema version mismatch: Maximum schema version supported is 3.0.0, but found 4.0.0.
```

### PR DESCRIPTION
**Pull request by clebert**
This change fixes problems with the size of cloud formation templates for projects with many S3 files.
Closes #98

### CODE REVIEW

**Comment by clebert** [comment]
@palasjir @unstubbable 

This PR resets the mechanics regarding S3 integrations to the status before version 2.0.1. This should fix the problems from issue #98 . It would help if you both test your projects with this version (via `yarn link`). Besides the real deployment on AWS, please also focus on testing the DEV server.

**Comment by palasjir** [comment]
@clebert 
I tried the update and run into following problem when running the deploy with linked version:

```
TypeError: Cannot read property 'replace' of undefined
    at sanitizeId (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/constructs/lib/construct.js:534:15)
    at Node.tryFindChild (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/constructs/lib/construct.js:73:31)
    at ConstructNode.tryFindChild (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/@aws-cdk/core/lib/construct-compat.js:226:48)
    at LegacyStackSynthesizer.doAddFileAsset (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/@aws-cdk/core/lib/stack-synthesizers/legacy.js:117:48)
    at LegacyStackSynthesizer.addFileAsset (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/@aws-cdk/core/lib/stack-synthesizers/legacy.js:57:25)
    at Stack.addFileAsset (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/@aws-cdk/core/lib/stack.js:348:33)
    at LegacyStackSynthesizer.addFileAsset (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/@aws-cdk/core/lib/stack-synthesizers/legacy.js:61:31)
    at new Asset (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/@aws-cdk/aws-s3-assets/lib/asset.js:34:44)
    at AssetCode.bind (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/@aws-cdk/aws-lambda/lib/code.js:136:26)
    at new Function (/Users/jiri.palas/dev/s2/vw/aws-simple/node_modules/@aws-cdk/aws-lambda/lib/function.js:69:33)
```

**Comment by clebert** [comment]
Maybe this is a compatibility problem between `constructs` and your CDK version. Can you check your Lockfile and update to the latest versions?

**Comment by clebert** [comment]
@palasjir I've discovered a potential problem. I have always declared the`constructs` library as my own dependency. But I do not use it directly. I have now changed it so that I declare all CDK libraries I use directly as peer dependencies. I don't declare constructs at all anymore. If you upgrade to CDK 1.45 in your project and make sure that the correct`constructs` library is installed, everything should work.

**Comment by palasjir** [comment]
Maybe i'm doing something wrong with linking but i've forced all `@aws-cdk/*` packages to correspond with version `1.45.0` but that then produces following error:
```
Error: There is already a Construct with name '{file}' in Resource [feature-app]
```

**Comment by palasjir** [comment]
Maybe i'm doing something wrong with linking the package but i've tried to make all the `@aws-cdk/*` resolve to version `1.45.0` but it's still giving the same error.

**Comment by clebert** [comment]
I cannot reproduce your issue on my side. I have tested the linked version with 3 different applications. @unstubbable Did you experience the same issues?

**Comment by unstubbable** [comment]
@clebert @palasjir We also have the error in `sanitizeId`:

```
TypeError: Cannot read property 'replace' of undefined
    at sanitizeId (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/constructs/lib/construct.js:534:15)
    at Node.tryFindChild (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/constructs/lib/construct.js:73:31)
    at ConstructNode.tryFindChild (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/@aws-cdk/core/lib/construct-compat.js:226:48)
    at LegacyStackSynthesizer.doAddFileAsset (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/@aws-cdk/core/lib/stack-synthesizers/legacy.js:117:48)
    at LegacyStackSynthesizer.addFileAsset (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/@aws-cdk/core/lib/stack-synthesizers/legacy.js:57:25)
    at Stack.addFileAsset (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/@aws-cdk/core/lib/stack.js:348:33)
    at LegacyStackSynthesizer.addFileAsset (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/@aws-cdk/core/lib/stack-synthesizers/legacy.js:61:31)
    at new Asset (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/@aws-cdk/aws-s3-assets/lib/asset.js:34:44)
    at AssetCode.bind (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/@aws-cdk/aws-lambda/lib/code.js:136:26)
    at new Function (/Users/hendrik.liebau/code/oss/aws-simple/node_modules/@aws-cdk/aws-lambda/lib/function.js:69:33)
```

Maybe we should test this with a real prerelease (published to npm with `next` tag) instead of linking it which might lead to weird dependency issue especially with regards to your latest peer dependencies change?

**Comment by unstubbable** [comment]
Otherwise, the dev server works without any issues so far.

**Comment by unstubbable** [comment]
I also completed the code review. Looks good to me!

**Comment by clebert** [comment]
@unstubbable @palasjir I have just published version 3.2.0 as aws-simple@next as suggested by Hendrik. Can you please test this version again?

**Comment by clebert** [comment]
I have unpublished version `3.2.0` and published `4.0.0-rc1` instead.

**Comment by clebert** [comment]
I will then merge it. We have successfully tested this PR with several productive projects. Thanks for your help.

**Pull request merged**
